PREFIX qb:    <http://purl.org/linked-data/cube#>
PREFIX code:  <http://code-research.eu/resource/>
PREFIX rdf:   <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs:  <http://www.w3.org/2000/01/rdf-schema#>
PREFIX va:    <http://code-research.eu/ontology/visual-analytics#>
PREFIX prov:  <http://www.w3.org/ns/prov#>
PREFIX dc:    <http://purl.org/dc/elements/1.1/>

SELECT ?component ?concept
WHERE {
    GRAPH ?g {
        ?d rdf:type qb:DataSet .
        ?d qb:structure ?dsd .
        ?dsd rdf:type qb:DataStructureDefinition .
        ?dsd qb:component ?comp .
        ?comp ?component ?concept
    }
}